baseURL = "http://joseluiz.net/"
disqusShortname = "joseluiz"
googleAnalytics = "UA-115448344-1"
adsenseDataAdClient = ""
adsenseDataAdSlot = ""
baseURLImages = "https://i.imgur.com/"

defaultContentLanguage = "en"
enableEmoji = true
languageCode = "en"
paginate = 10
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"

[params]
  description = "José Luiz - Artigos sobre C#, Entity Framework, SQL e desenvolvimento software"
  keywords = "Javascript, React.js, React Native, Node.js, .Net Core, SQL, MariaDB"
  copyright = "© José Luiz"
  licence = ""
  addnavleft = "true"
  addThisId = "ra-5aa2dff90bb5f212"


[languages]
  [languages.en]
    title = "Article about Software Development using tech:  Javascript, React.Js, React Native, Node.Js, .Net Core, SQL & MariaDB"
    description = "Article about Software Development using tech:  Javascript, React.Js, React Native, Node.Js, .Net Core, SQL & MariaDB"
    weight = 1


 [languages.pt]
    title = "José Luiz - Artigos sobre Desenvovimento de Software, C#, Entity Framework, SQL e Empreendedorismo"
    description = "José Luiz - Artigos sobre C#, Entity Framework, SQL e desenvolvimento software"
    weight = 2


[author]
  gravatarEmail = "test@example.com"
  homepageText = "José Luiz"
  name = "José Luiz"


[permalinks]
  # posts = "/:year/:month/:day/:slug/"
  posts = "/:slug/"
[pygmentsOptions]
  linenos = false

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
