baseURL = "https://joseluiz.azurewebsites.net/"
defaultContentLanguage = "en"
enableEmoji = true
languageCode = "pt-br"
paginate = 4
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "José Luiz -  Blog Site"
[author]
  gravatarEmail = "test@example.com"
  homepageText = "José Luiz"
  name = "José Luiz"
[params]
  description = "Blog José Luiz sobre SQL, .Net AI"
  disqusShortname = "joseluiz"
  googleAnalytics = "UA-115448344-1"
  licence = ""
  adsenseDataAdClient = ""
  adsenseDataAdSlot = ""
  addnavleft = ""
  addThisId = "ra-5aa2dff90bb5f212"
[permalinks]
  # posts = "/:year/:month/:day/:slug/"
  posts = "/:slug/"
[pygmentsOptions]
  linenos = false
[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
