baseURL = "http://joseluiz.net/"

disqusShortname = "joseluiz"
googleAnalytics = "UA-115448344-1"
adsenseDataAdClient = ""
adsenseDataAdSlot = ""
baseURLImages = "https://i.imgur.com/"

defaultContentLanguage = "pt"
enableEmoji = true
languageCode = "pt-br"
paginate = 5
pygmentsCodeFences = true
pygmentsStyle = "native"
pygmentsUseClasses =  true
theme = "simplicity"
title = "José Luiz - Artigos sobre C#, Entity Framework, SQL e desenvolvimento software"


[author]
  gravatarEmail = "test@example.com"
  homepageText = "José Luiz"
  name = "José Luiz"

[params]
  description = "José Luiz - Artigos sobre C#, Entity Framework, SQL e desenvolvimento software"
  keywords = ".Net, C#, Entity Framework, SQL, T-SQL"
  copyright = "© 2018 José Luiz"
  licence = ""
  addnavleft = ""
  addThisId = "ra-5aa2dff90bb5f212"

[permalinks]
  # posts = "/:year/:month/:day/:slug/"
  posts = "/:slug/"
[pygmentsOptions]
  linenos = false

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
[[menu.pages]]
  name = "Projects"
  weight = -100
  identifier = "projects"
  url = "/projects/"
[[menu.pages]]
  name = "Photos"
  weight = -90
  identifier = "photos"
  url = "/photos/"
